import Vapor

extension Configure {
  static func migrations(_ app: Application) throws {
    app.migrations.add(CreateDownloads())
    app.migrations.add(CreateOrders())
    app.migrations.add(CreateOrderItems())
    app.migrations.add(CreateTokens())
    app.migrations.add(CreateTokenScopes())
    app.migrations.add(CreateFreeOrderRequests())
    app.migrations.add(AddOrderRequestId())
    app.migrations.add(CreateArtifactProductionVersions())
    app.migrations.add(AddMutateArtifactProductionVersionScope())
    app.migrations.add(HandleEditionIds())
    app.migrations.add(CreateFriends())
    app.migrations.add(CreateFriendResidences())
    app.migrations.add(CreateFriendQuotes())
    app.migrations.add(CreateDocuments())
    app.migrations.add(CreateTags())
    app.migrations.add(AddShippingLevelGroundBus())
    app.migrations.add(CreateEditions())
    app.migrations.add(CreateEditionImpressions())
    app.migrations.add(CreateIsbns())
    app.migrations.add(CreateAudios())
    app.migrations.add(CreateAudioParts())
    app.migrations.add(CreateEditionChapters())
    app.migrations.add(CreateRelatedDocuments())
    app.migrations.add(AddTokenScopes())
    app.migrations.add(CreateFriendResidenceDurations())
    app.migrations.add(AddEditionIdForeignKeys())
    app.migrations.add(AddTokenUses())
    app.migrations.add(AddOrderFeesColumn())
    app.migrations.add(DropFriendResidenceDurationCol())
    app.migrations.add(BackfillLocationData())
    app.migrations.add(RemoveDuplicatePodcastDownloads())
    app.migrations.add(BigIntToInt())
    app.migrations.add(SeedTokens())
  }
}
