_default:
  @just --choose

dev-en: write-cover-css
  @NEXT_PUBLIC_LANG=en pnpm next dev --port 7222

dev-es: write-cover-css
  @NEXT_PUBLIC_LANG=es pnpm next dev --port 7333

build-en: write-cover-css
  @NEXT_PUBLIC_LANG=en pnpm next build

build-es: write-cover-css
  @NEXT_PUBLIC_LANG=es pnpm next build

storybook:
  @cd ../../ && pnpm --filter storybook storybook

test:
  @pnpm vitest . --watch

# helpers

[private]
write-cover-css:
  @pnpm ts-node ./lib/ssg/cover-static-css.ts
