_default:
  @just --choose

dev-en:
  @NEXT_PUBLIC_LANG=en pnpm dev --port 7222

dev-es:
  @NEXT_PUBLIC_LANG=es pnpm dev --port 7333

prisma-generate: cp-env && rm-env
  @pnpm prisma generate

# helpers

[private]
cp-env:
  @cp ../../.env ./.env

[private]
rm-env:
  @rm ./.env
