// ******************************************
## complex footnote [ebook]
// ******************************************

****
God has exalted above every name, "`that at`" or in^
footnote:[J. G. Bevan`'s [.book-title]#Life of Paul,# note, page 363.]
"`the name of Jesus, every knee should bow.`"
****

++++
<p class="paragraph">
  God has exalted above every name, “that at” or in
  <sup class="footnote" id="fn-call__2">
    <a href="notes.xhtml#fn__2" title="View footnote.">*</a>
  </sup>
  “the name of Jesus, every knee should bow.”
</p>
++++

// ******************************************
## chapter heading has id [ebook]
// ******************************************

****
[#preface, short="Pre"]
== Preface

Hello world.
****

++++
<div id="preface" class="chapter chapter-1 chapter--no-signed-section">
  <header class="chapter-heading" data-short="Pre">
    <h2>Preface</h2>
  </header>
  <p class="paragraph">Hello world.</p>
</div>
++++

// ******************************************
## ebook footnote call markup [ebook]
// ******************************************

****
Hello world.footnote:[A note.]
****

++++
<p class="paragraph">
  Hello world.
  <sup class="footnote" id="fn-call__2">
    <a href="notes.xhtml#fn__2" title="View footnote.">*</a>
  </sup>
</p>
++++

// ******************************************
## multiple ebook call footnote markup [ebook]
// ******************************************

****
Hellofootnote:[Note 1.] world.footnote:[Note 2.]
****

++++
<p class="paragraph">
  Hello
  <sup class="footnote" id="fn-call__2">
    <a href="notes.xhtml#fn__2" title="View footnote.">*</a>
  </sup>
  world.
  <sup class="footnote" id="fn-call__3">
    <a href="notes.xhtml#fn__3" title="View footnote.">†</a>
  </sup>
</p>
++++

// ******************************************
## numbered ebook call footnote markup [ebook]
// ******************************************

****
Hello^
footnote:[Note 1.]
there^
footnote:[Note 2.]
you^
footnote:[Note 3.]
world^
footnote:[Note 4.]
****

++++
<p class="paragraph">
  Hello
  <sup class="footnote" id="fn-call__2">
    <a href="notes.xhtml#fn__2" title="View footnote.">2</a>
  </sup>
  there
  <sup class="footnote" id="fn-call__3">
    <a href="notes.xhtml#fn__3" title="View footnote.">3</a>
  </sup>
  you
  <sup class="footnote" id="fn-call__4">
    <a href="notes.xhtml#fn__4" title="View footnote.">4</a>
  </sup>
  world
  <sup class="footnote" id="fn-call__5">
    <a href="notes.xhtml#fn__5" title="View footnote.">5</a>
  </sup>
</p>
++++

// ******************************************
## cross-chapter cross-reference links [ebook]
// ******************************************

****
== Preface

Hello <<note-A,world.>>

== Introduction

[#note-A]
=== Note A

Here is a note.
<<note-A__xref_src,?LINKABLE-BACK>>
****

++++
<div id="chapter-1" class="chapter chapter-1 chapter--no-signed-section">
  <header class="chapter-heading" data-short="Preface">
    <h2>Preface</h2>
  </header>
  <p class="paragraph">
    Hello
    <a id="note-A__xref_src" class="__xref" href="chapter-2.xhtml#note-A">world.</a>
  </p>
</div>
<div id="chapter-2" class="chapter chapter-2 chapter--no-signed-section">
  <header class="chapter-heading" data-short="Introduction">
    <h2>Introduction</h2>
  </header>
  <h3 id="note-A">Note A</h3>
  <p class="paragraph">
    Here is a note.
    <a class="__xref __xref-linkable-back" href="chapter-1.xhtml#note-A__xref_src">
       &#9166; 
    </a>
  </p>
</div>
++++
