// ********************************
## hello world
// ********************************

****
== Preface

Hello **there** __world.__
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <p>Hello <b>there</b> <em>world.</em></p>
</div>
++++

// ********************************
## curly quotes
// ********************************

****
== "`Introduction`"

'`Hello`' "`world.`"
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>“Introduction”</h2></header>
  <p>‘Hello’ “world.”</p>
</div>
++++

// ********************************
## chapter context
// ********************************

****
[#intro.style-blurb, short="Short Title"]
== Preface

Hello world.
****

++++
<div id="intro" class="chapter chapter-1 style-blurb" data-short-title="Short Title">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <p>Hello world.</p>
</div>
++++

// ********************************
## multiple chapters
// ********************************

****
== Preface

Hello __world.__
****

****
== Intro

Goodbye world.
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <p>Hello <em>world.</em></p>
</div>
<div class="chapter chapter-2">
  <header class="chapter-heading"><h2>Intro</h2></header>
  <p>Goodbye world.</p>
</div>
++++

// ********************************
## paragraph classes
// ********************************

****
== Preface

[.offset]
Hello world.
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <p class="offset">Hello world.</p>
</div>
++++

// ********************************
## embedded letter
// ********************************

****
== Preface

[.embedded-content-document.letter]
--

[.salutation]
Friend,

Hello world.

[.signed-section-signature]
George Fox

--
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <div class="embedded-content-document letter">
    <p class="salutation">Friend,</p>
    <p>Hello world.</p>
    <p class="signed-section-signature">George Fox</p>
  </div>
</div>
++++

// ********************************
## syllogism
// ********************************

****
== Preface

[.syllogism]
* Item 1
* Item 2
* Item 3
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <ul class="syllogism">
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
  </ul>
</div>
++++

// ********************************
## footnotes
// ********************************

****
== Preface.footnote:[Note _one._]

Hello world.^
footnote:[Note two.]

Goodbye world.^
footnote:[Note
{footnote-paragraph-split}
three.]
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading">
    <h2>Preface.<span class="footnote">Note <em>one.</em></span></h2>
  </header>
  <p>Hello world.<span class="footnote">Note two.</span></p>
  <p>
    Goodbye world.
    <span class="footnote">
      <span class="footnote-paragraph">Note</span>
      <span class="footnote-paragraph">three.</span>
    </span>
  </p>
</div>
++++

// ********************************
## footnote with poetry
// ********************************

****
== Preface

Hello world.^
footnote:[Footnotes can have poetry:
`    Foo bar,
     So much baz.
     - - - - - -
     Foo bar
     And baz. `
Some text after.]
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <p>
    Hello world.
    <span class="footnote">
      <span class="footnote-paragraph">Footnotes can have poetry:</span>
      <span class="poetry">
        <span class="verse-stanza">
          <span class="verse-line">Foo bar,</span>
          <span class="verse-line">So much baz.</span>
        </span>
        <span class="verse-stanza">
          <span class="verse-line">Foo bar</span>
          <span class="verse-line">And baz.</span>
        </span>
      </span>
      <span class="footnote-paragraph">Some text after.</span>
    </span>
  </p>
</div>
++++

// ********************************
## block quotes
// ********************************

****
== Preface

[quote.scripture, , ]
____
A single paragraph quote.
____

[quote.scripture, , John 1:1]
____
In the beginning was the Word.

And the Word was with God.
____

[quote, Bob Barclay, Apology]
____
Ask not what your country can do for you.
____
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <blockquote class="scripture">
    <p>A single paragraph quote.</p>
  </blockquote>
  <figure class="attributed-quote scripture">
    <blockquote class="scripture">
      <p>In the beginning was the Word.</p>
      <p>And the Word was with God.</p>
    </blockquote>
    <figcaption>
      <cite>John 1:1</cite>
    </figcaption>
  </figure>
  <figure class="attributed-quote">
    <blockquote>
      <p>Ask not what your country can do for you.</p>
    </blockquote>
    <figcaption>
      <span class="quote-attribution">&#8212; Bob Barclay</span>
      <cite>Apology</cite>
    </figcaption>
  </figure>
</div>
++++

// ********************************
## segmented h3
// ********************************

****
== Preface

[.old-style]
=== Part 1 / Part 2 / Part 3

Hello world.
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <h3 class="old-style">
    <span>Part 1</span>
    <span>Part 2</span>
    <span>Part 3</span>
  </h3>
  <p>Hello world.</p>
</div>
++++

// ********************************
## numbered-group
// ********************************

****
== Preface

[.numbered-group]
====

[.numbered]
Item 1.

[.numbered]
Item 2.

[.numbered]
Item 3.

Item 3, paragraph 2.

====
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <div class="numbered-group">
    <div class="numbered">
      <p>Item 1.</p>
    </div>
    <div class="numbered">
      <p>Item 2.</p>
    </div>
    <div class="numbered">
      <p>Item 3.</p>
      <p>Item 3, paragraph 2.</p>
    </div>
  </div>
</div>
++++

// ********************************
## description lists
// ********************************

****
== Preface

Term:: definition.

Another term::
A longer _definition._
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <dl>
    <dt>Term</dt>
    <dd>definition.</dd>
    <dt>Another term</dt>
    <dd>A longer <em>definition.</em></dd>
  </dl>
</div>
++++

// ********************************
## poetry
// ********************************

****
== Preface

[verse]
____
Foo bar
So much baz
____

[verse]
____
Foo bar
So much baz

A second stanza
with some more baz.
____
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <section class="poetry">
    <div class="verse-stanza">
      <span class="verse-line">Foo bar</span>
      <span class="verse-line">So much baz</span>
    </div>
  </section>
  <section class="poetry">
    <div class="verse-stanza">
      <span class="verse-line">Foo bar</span>
      <span class="verse-line">So much baz</span>
    </div>
    <div class="verse-stanza">
      <span class="verse-line">A second stanza</span>
      <span class="verse-line">with some more baz.</span>
    </div>
  </section>
</div>
++++

// ********************************
## asterism and small break
// ********************************

****
== Preface

Hello world.

[.asterism]
'''

Still here world.

[.small-break]
'''

Goodbye world.
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <p>Hello world.</p>
  <div class="asterism">*&#160;&#160;*&#160;&#160;*</div>
  <p>Still here world.</p>
  <div class="small-break"></div>
  <p>Goodbye world.</p>
</div>
++++

// ********************************
## discourse part
// ********************************

****
== Preface

[.discourse-part]
__Landlord.__ So John, you are busy?

[.discourse-part]
Answer 32: yes indeed.
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <p class="discourse-part">
    <em>Landlord.</em> So John, you are busy?
  </p>
  <p class="discourse-part">
    <em>Answer 32:</em> yes indeed.
  </p>
</div>
++++

// ********************************
## chapter synopsis
// ********************************

****
== Preface

[.chapter-synopsis]
* Item _one_.
* Item "`two.`"
* Item 3.footnote:[beep boop]
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <ul class="chapter-synopsis">
    <li>Item <em>one</em>.</li>
    <li>Item “two.”</li>
    <li>Item 3.<span class="footnote">beep boop</span></li>
  </ul>
</div>
++++

// ********************************
## just chapter sequence
// ********************************

****
== Chapter 17.

Hello world
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading">
    <h2>Chapter XVII</h2>
  </header>
  <p>Hello world</p>
</div>
++++

// ********************************
## chapter sequence + title
// ********************************

****
== Chapter 1. Beep boop

Hello world
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading">
    <h2 class="chapter-heading__sequence">
      Chapter <span class="chapter-heading__sequence__number">I</span>
    </h2>
    <div class="chapter-heading-title">Beep boop</div>
  </header>
  <p>Hello world</p>
</div>
++++

// ********************************
## chapter sequence + segmented title
// ********************************

****
== Capítulo 1. Beep / Boop

Hello world
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading">
    <h2 class="chapter-heading__sequence">
      Capítulo <span class="chapter-heading__sequence__number">I</span>
    </h2>
    <div class="chapter-heading-title">
      <span>Beep</span>
      <span>Boop</span>
    </div>
  </header>
  <p>Hello world</p>
</div>
++++

// ********************************
## chapter subtitle-blurb becomes h3
// ********************************

****
== Preface

[.chapter-subtitle--blurb]
Hello world.
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <h3 class="chapter-subtitle--blurb">Hello world.</h3>
</div>
++++

// ********************************
## misc formatting
// ********************************

****
== Preface

Barclay [.book-title]#Apology.#

This [.underline]#is underlined.#

Some +++[+++random square brackets+++]+++.
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <p>Barclay <span class="book-title">Apology.</span></p>
  <p>This <span class="underline">is underlined.</span></p>
  <p>Some [random square brackets].</p>
</div>
++++

// ********************************
## postscript
// ********************************

****
== Preface

[.postscript]
====

P+++.+++ S.--Hello world.

====
****

++++
<div class="chapter chapter-1">
  <header class="chapter-heading"><h2>Preface</h2></header>
  <div class="postscript">
    <p>
     <em>P. S.</em>—Hello world.
    </p>
  </div>
</div>
++++
