### Get Order

POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer {{stagingToken}}

query {
  counts: getModelsCounts {
    friends
  }
}


### Create an Order

POST {{endpoint}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer {{stagingToken}}

mutation CreateOrder($input: CreateOrderInput!) {
  order: createOrder(input: $input) {
    id
    paymentId
    printJobStatus
    shippingLevel
    email
    addressName
    addressStreet
    addressCity
    addressState
    addressZip
    addressCountry
    lang
    source
    items {
      title
      documentId
      editionType
      quantity
      unitPrice
    }
  }
}

{
  "input": {
    "paymentId": "stripe-123",
    "printJobStatus": "presubmit",
    "shippingLevel": "mail",
    "amount": 33,
    "shipping": 33,
    "taxes": 33,
    "ccFeeOffset": 33,
    "email": "jared@netrivet.com",
    "addressName": "Jared Henderson",
    "addressStreet": "123 Magnolia Lane",
    "addressCity": "New York",
    "addressState": "NY",
    "addressZip": "90210",
    "addressCountry": "US",
    "lang": "en",
    "source": "website",
    "items": [
      {
        "title": "Journal of George Fox",
        "documentId": "9050edba-197e-498f-9fb8-61c36abae59e",
        "editionType": "original",
        "quantity": 1,
        "unitPrice": 333
      }
    ]
  }
}
###

# @endpoint = http://127.0.0.1:8080/graphql
@endpoint = https://api-graphql.friendslibrary.com/graphql
@stagingToken = ab9e8fca-ba51-4e7e-b5d1-00d9269503ae
